### ISSUE TITLE
EFL

### ISSUE THREAD

**Issue by lina926** [ModelTC/United-Perception#17]
Where is the code of EFL

**Comment by Dream-High** [comment]
I have the same question. And I also have a question about how to extend the EFL to other models.

**Comment by xiaohe6** [comment]
> Where is the code of EFL
Hi, may I take the liberty to ask, have you found the EFL code?

**Comment by yqyao** [comment]
Here https://github.com/ModelTC/EOD/tree/main/eod/tasks/det/plugins/efl @lina926 @xiaohe6

**Comment by xiaohe6** [comment]
> Here https://github.com/ModelTC/EOD/tree/main/eod/tasks/det/plugins/efl @lina926 @xiaohe6

ok, thanks a lot

**Comment by xiaohe6** [comment]
> Here https://github.com/ModelTC/EOD/tree/main/eod/tasks/det/plugins/efl @lina926 @xiaohe6

Hi, I would like to take the liberty to ask you again, have you tried running this code? I don't know where to start running

**Comment by yqyao** [comment]
> > Here https://github.com/ModelTC/EOD/tree/main/eod/tasks/det/plugins/efl @lina926 @xiaohe6
> 
> Hi, I would like to take the liberty to ask you again, have you tried running this code? I don't know where to start running

https://github.com/ModelTC/EOD/blob/main/eod/commands/train.py，you can just follow the readme.

**Comment by xiaohe6** [comment]
> > > Here https://github.com/ModelTC/EOD/tree/main/eod/tasks/det/plugins/efl @lina926 @xiaohe6
> > 
> > 
> > Hi, I would like to take the liberty to ask you again, have you tried running this code? I don't know where to start running
> 
> [https://github.com/ModelTC/EOD/blob/main/eod/commands/train.py，you](https://github.com/ModelTC/EOD/blob/main/eod/commands/train.py%EF%BC%8Cyou) can just follow the readme.

ok，thanks， I will try it again

**Comment by Bio-shine** [comment]
> Where is the code of EFL

have anyone found the code of EFL?

**Comment by lina926** [comment]
> Here https://github.com/ModelTC/EOD/tree/main/eod/tasks/det/plugins/efl @lina926 @xiaohe6
404 can not open

**Comment by yqyao** [comment]
https://github.com/ModelTC/United-Perception/blob/main/up/tasks/det/plugins/efl/models/losses/efl.py @lina926
