### ISSUE TITLE
EOD/eod/models/heads/utils/bbox_helper.py", line 341, in clip_bbox     dw, dh = img_size[6], img_size[7] IndexError: list index out of range

### ISSUE THREAD

**Issue by jinfagang** [ModelTC/United-Perception#2]
I found in Inferece.py the prepare are:

```python
def fetch_single(self, filename):
        img = self.image_reader.read(filename)
        data = EasyDict(
            {"filename": filename, "origin_image": img, "image": img, "flipped": False}
        )
        data = self.transformer(data)
        scale_factor = data.get("scale_factor", 1)

        image_h, image_w = get_image_size(img)
        new_image_h, new_image_w = get_image_size(data.image)
        data.image_info = [
            new_image_h,
            new_image_w,
            scale_factor,
            image_h,
            image_w,
            data.flipped,
            filename,
        ]
        data.image = data.image.cuda()
        return data
```

which `image_info` max size is 7, so that above index [7] is out of indices. How to resolve?

**Comment by yqyao** [comment]
> I found in Inferece.py the prepare are:
> 
> ```python
> def fetch_single(self, filename):
>         img = self.image_reader.read(filename)
>         data = EasyDict(
>             {"filename": filename, "origin_image": img, "image": img, "flipped": False}
>         )
>         data = self.transformer(data)
>         scale_factor = data.get("scale_factor", 1)
> 
>         image_h, image_w = get_image_size(img)
>         new_image_h, new_image_w = get_image_size(data.image)
>         data.image_info = [
>             new_image_h,
>             new_image_w,
>             scale_factor,
>             image_h,
>             image_w,
>             data.flipped,
>             filename,
>         ]
>         data.image = data.image.cuda()
>         return data
> ```
> 
> which `image_info` max size is 7, so that above index [7] is out of indices. How to resolve?

https://github.com/ModelTC/EOD/blob/a45b74430070d82d9248a10fb5e1116bb7ababe1/eod/data/datasets/coco_dataset.py#L297.  This is a bug for yolov5 (center pad) inference, we will fix it later

**Comment by Joker-co** [comment]
@jinfagang The bug has been fixed.

**Comment by jinfagang** [comment]
@Joker-co can we have a demo.py sinply read a image as input and show result? Don't involve with any dataloader so that it can easily use and quickly vis final result.

**Comment by yqyao** [comment]
We think the demo now seems to be able to meet the demand. Config is necessary in order to parse the test configuration, and we don't build dataloader. @jinfagang

**Comment by jinfagang** [comment]
@yqyao something like this could be better, whole code easy to modification rather than deeply wrapped inside EOD package.

And this demo give wrong result:

https://github.com/ModelTC/EOD/issues/3#issuecomment-956043047
