### ISSUE TITLE
from .._C import xxx, error

### ISSUE THREAD

**Issue by EthanChen1234** [ModelTC/United-Perception#24]
hi, i'm got the error 'ImportError: cannot import name 'naive_nms' from 'up.extensions.csrc' (unknown location)'

![e2a77bc3246af8301ca528b4df54a23c](https://user-images.githubusercontent.com/45474996/176637489-f8c1965f-0da9-4a9f-a212-b408d841510d.png)

for the naive_nms, it's not in csrc? where it is?

**Comment by yqyao** [comment]
https://github.com/ModelTC/United-Perception/blob/main/up/extensions/csrc/pybind.cpp#L57 @EthanChen1234
