### ISSUE TITLE
运行自带的retinanet配置失败

### ISSUE THREAD

**Issue by wangshankun** [ModelTC/United-Perception#34]
```
Error log:
dimensions of scale and zero-point are not consistent with input tensor；
```
运行指令：时候加上一次evaluate，原始pretrain模型无法运行；
![image](https://user-images.githubusercontent.com/3970271/182093712-049e9250-68c4-4283-8df8-f08c73276dfa.png)

![image](https://user-images.githubusercontent.com/3970271/182093533-a5b48728-46d8-4bea-894b-36c21ec5f2ea.png)

**Comment by PannenetsF** [comment]
ckpt可能加载的是fp32的，需要加载量化训练完成后的ckpt

**Comment by wangshankun** [comment]
> ckpt可能加载的是fp32的，需要加载量化训练完成后的ckpt

嗯，这个是量化之前，先评估org fp32模型的

**Comment by PannenetsF** [comment]
换成base runner
