### ISSUE TITLE
怎么在分类任务中修改并使用EFL？

### ISSUE THREAD

**Issue by Prot-debug** [ModelTC/United-Perception#37]
我看到您在 [issue 11](https://github.com/ModelTC/United-Perception/issues/11) 中回答了在分类任务中如何使用EFL的相关问题，但我对其中的第二点不是十分明白，我应该怎么修改我的梯度指导策略才能更好地应用在分类任务上呢？您能提供一些参考的代码或者给出一些代码上修改的建议吗？谢谢！

**Comment by yqyao** [comment]
https://github.com/ModelTC/United-Perception/commit/0aed4a2298038fc9ab6b04cb53a83314505db39d。 @Prot-debug

**Comment by Prot-debug** [comment]
> [0aed4a2298038fc9ab6b04cb53a83314505db39d。](https://github.com/ModelTC/United-Perception/commit/0aed4a2298038fc9ab6b04cb53a83314505db39d。) @Prot-debug

您好，你发的这个链接，我打开显示拒绝访问，看不到内容。

**Comment by yqyao** [comment]
https://github.com/ModelTC/United-Perception/commit/0aed4a2298038fc9ab6b04cb53a83314505db39d , this commit @Prot-debug
