### ISSUE TITLE
Use Softmax Equalization Loss to object  Recongnition in LVIS dataset 

### ISSUE THREAD

**Issue by Never-Walk-Away** [ModelTC/United-Perception#49]
Hello Author, you're doing a great job. I would like to ask how the Softmax-EQL function proposed in this paper can be used in target detection.

**Comment by yqyao** [comment]
https://arxiv.org/abs/2210.05566, 
![image](https://user-images.githubusercontent.com/20680893/203727419-84807603-d434-427d-9937-b4a63b92a33d.png)
@Never-Walk-Away

**Comment by Never-Walk-Away** [comment]
thanks!
