### ISSUE TITLE
多卡训练错误

### ISSUE THREAD

**Issue by hxy0307** [ModelTC/United-Perception#63]
ng=1时可以正常训练，但是ng>1时就会出错，想问问原版本的python，pytorch以及cuda的版本，我的错误如下：
<img width="1996" alt="WeChatcedc134115b20190ba1c9d6cdd5d3337" src="https://user-images.githubusercontent.com/29944418/231063823-920737e8-58b1-48b5-a4ae-283444d49fee.png">

**Comment by yqyao** [comment]
pytorch1.8.1 cuda9.0 or cuda11.2 is ok, python3.6 @hxy0307
